project:
  type: website

website:
  title: "Kane's Free Data Science Course"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Testimonials"
        href: testimonials.qmd
      - text: "Staff"
        href: staff.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Final Projects"
        href: projects.qmd
      - text: "Demo Day"
        href: demo_day.qmd
exclude:
  - internal
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



