---
title: "Schedule"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**THIS IS AN INCOMPLETE DRAFT SCHEDULE**

**Submit your homework answers, as an html file, via [this Google form](https://forms.gle/j3hBXL1XT3JMiscN8) before midnight on the day before the class for which the homework was assigned.**


Key resources: [*R for Data Science (2e)*](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund, [*Preceptor's Primer for Bayesian Data Science*](https://ppbds.github.io/primer/) by David Kane, [*Analyzing US Census Data: Methods, Maps, and Models in R*](https://walker-data.com/census-r/) by Kyle Walker. 

See the home pages for [**positron.tutorials**](https://ppbds.github.io/positron.tutorials/), [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/), [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/), and [**tidycensus.tutorials**](https://ppbds.github.io/tidycensus.tutorials/) for installation instructions.

Always reinstall the relevant package before starting a new tutorial. Example for **primer.tutorials**:

```
remove.packages("primer.tutorials")
remotes::install_github("PPBDS/primer.tutorials")
```

We are always fixing mistakes. You want to use the latest version.


If you do not complete the tutorials on time, you will be removed from the class. Send in your tutorial answers saved in *html* format. Please try to ensure that the name of the file is the default name, like `tutorials-in-positron_answers.html`. Avoid using the name which will be assigned to the file if you download the same answers twice (or more), stuff like `tutorials-in-positron_answers (2).html`. You can just change the name of the file by hand if this happens.


# Registration

Do not start the registration process yet.

<!-- To register for the class and reserve your spot, please read [Getting Started with Positron](https://ppbds.github.io/primer/getting-started-with-positron.html) and follow all the associated instructions. Complete the "Getting Started with Tutorials" tutorial from the [**tutorial.helpers**](https://ppbds.github.io/tutorial.helpers/) package.  -->

# Week 1: June 16

Looking at the data is the first step in data science. Note that Monday's homework must be completed before Monday's class. I ensure this by only sending the Zoom link for class to students who submitted the homework.

## Monday 

* Read the Introduction from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Introduction" (`00-introduction`) tutorial. 

* From the [**positron.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Positron and Code" (`01-code`) tutorial. Make sure that you have already completed the "Introduction" tutorial above before you start the "Positron and Code" tutorial.

## Wednesday

* From the [**positron.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Positron and Quarto" (`02-quarto`) and "Terminal" (`03-terminal`) tutorials.

* Read Chapters 1 - 3 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Data visualization" (`01-data-visualization`) and "Data transformation" (`03-data-transformation`) tutorials. 

**Reminder**: All work must be completed before class. Failure to submit your tutorial answers will result in you being removed from the course. It is not fair to your fellow students, with whom you will be working in small groups, for you to not be prepared for class.


## Thursday 

* From the [**positron.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Positron and GitHub Introduction" (`04-github-1`) tutorial.

* Read [Cardinal Virtues](https://ppbds.github.io/primer/cardinal-virtues.html).


# Week 2: June 23

Now that we know how to visualize data that is already clean, we need to learn how to clean up messy data. 

## Monday 

* Read [Chapter 1 Rubin Causal Model](https://ppbds.github.io/primer/rubin-causal-model.html) and complete the "Rubin Causal Model" tutorial (`011-rubin-causal-model`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  


* From the [**positron.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Positron and GitHub Advanced" (`05-github-2`) tutorial.


* Read Chapters 4 and 5 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Data tidying" (`05-data-tidying `). 
 

## Wednesday

* Read [Chapter 2 Probability](https://ppbds.github.io/primer/probability.html) and complete the "Probability" tutorial (`021-probability`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  

## Thursday 

* Read [Chapter 3 Sampling](https://ppbds.github.io/primer/probability.html) and complete the "Sampling" tutorial (`031-Sampling`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  


* Read Chapters 9, 10 and 11 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/), and from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the tutorials associated with the readings: "Layers," "Exploratory Data Analysis," and "Communication."  


* Read chapters 1 and 2 from from [*Analyzing US Census Data: Methods, Maps, and Models in R*](https://walker-data.com/census-r/index.html) by Kyle Walker. The U.S. Census is a great source of data for your projects.


* From the [**tidycensus.tutorials**](https://ppbds.github.io/tidycensus.tutorials/) package, complete the "An introduction to tidycensus" tutorial.  

* Read [Cardinal Virtues](https://ppbds.github.io/primer/cardinal-virtues.html).

# Week 3: June 30

## Monday 

* Read [Chapter 4 Models](https://ppbds.github.io/primer/models.html) and complete the "Models" tutorial (`041-Models`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  



* From the [**positron.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Quarto Websites Introduction" (`06-websites-1`) and "Quarto Websites Advanced" (`07-websites-2`) tutorials.


* Read chapters 12, 13, 28 and 29 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Logical vectors," "Numbers," and "Quarto Websites" tutorials.

* Come to class with the url for at least one data source you will be using for your Data Project.


## Wednesday

* Read [Chapter 5 Two Parameters](https://ppbds.github.io/primer/two-parameters.html) and complete the "Two Parameters" tutorial (`051-two-parameters`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  

## Thursday 

* Read [Chapter 6 Three Parameters: Causal](https://ppbds.github.io/primer/three-parameters-causal.html) and complete the "Three Parameters: Causal" tutorial (`061-three-parameters-causal`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  

* Read chapters 14, 15 and 16 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Strings," "Regular expressions" and "Factors" tutorials. 

* Read [Cardinal Virtues](https://ppbds.github.io/primer/cardinal-virtues.html).

# Week 4: July 7

The main focus on the 4th week is individual presentations of your Data Project. Do you love soccer or wine or NYC politics? The Data Project provides you with an opportunity to study that topic in depth. Your Data Project will be, for most of you, the first item in your professional portfolio, something so impressive that you will be eager to show it to graduate schools or potential employers.

<!-- DK: Add back in the final project tutorial. -->

## Monday

* Read [Chapter 7 Mechanics](https://ppbds.github.io/primer/mechanics.html) and complete the "Mechanics" tutorial (`071-mechanics`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  

* Read chapter 17 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Dates and times" tutorial.

* Complete the "Data Project" tutorial from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package. Be sure to reinstall the package before starting the tutorial.

## Wednesday 

* Read [Chapter 8 Four Parameters: Categorical](https://ppbds.github.io/primer/four-parameters-categorical.html) and complete the "Four Parameters: Categorical" tutorial (`081-four-parameters-categorical`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package.  

* Read chapter 18 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Missing values" tutorial.

* Practice presentations and feedback. You must have your presentation ready to go! 

## Thursday 

* Read [Chapter 9 Five Parameters](https://ppbds.github.io/primer/five-parameters.html) and complete the "Five Parameters" tutorial (`091-five-parameters`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package. 

* Read [Cardinal Virtues](https://ppbds.github.io/primer/cardinal-virtues.html).

# Week 5: July 14

## Monday

* Read [Chapter 10 N Parameters](https://ppbds.github.io/primer/n-parameters.html) and complete the "N Parameters" tutorial (`101-n-parameters`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package. 


* Read chapter 19 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Joins" tutorial.

## Wednesday

* Complete the "Cumulative" tutorial (`111-cumulative`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package. 

* Read chapter 20 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Spreadsheets" tutorial.


## Thursday

* Complete the "Stops" tutorial (`131-stops`) from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package. 

* Read chapter 21 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Databases" tutorial.


# Week 6: July 21

## Monday



## Wednesday


## Thursday

* Read chapter 22 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Arrow" tutorial. 

* Read chapter 23 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Hierarchical data" tutorial. 


# Week 7: July 28

## Monday


## Wednesday


* Read chapter 24 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Web scraping" tutorial. 

* Read chapter 25 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Functions" tutorial. 



## Thursday


* Read chapter 26 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Iteration" tutorial. 

* Read chapter 27 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "A field guide to base R" tutorial. 


# Week 8: August 4

The last week will consist of projects that the students will make. 


## Monday 

* From the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Project" tutorial before class, or you will be removed the course. There are no extensions for this assignment.

* You must have a draft of your final project ready to go, including a Quarto website and your paragraph introduction. 


## Wednesday 

* Practice presentations and feedback. You must have your presentation ready to go! 

## Thursday 

* Final project presentations. You must invite someone, and bcc your TF when you do so.
