---
title: "Day 1"
author: "David Kane"
---

## Goal

Do something with World Cup data. Students have done some stuff with AI in the quarto tutorial. Make a plot. Share the image in #class-work. Check out #tutorials and #announcements (only for course staff).

### Advice

Class exercises need to be very paced, with lots of tiny steps, each a script replacement. Always have a student share their screen. make sure that the text is big enough for people to easily see. You drive. You tell the student what to look at. You tell the student what to copy/paste. You tell the student what to ask the AI. Switch from student to student to ensure that everyone is engaged. Unlike last year, another student does not drive, at least this week. You drive. 

### Scene 0

Go through Preceptor Notes. Stop at after 1). Make sure people can share.

### Scene 1

Preceptor Notes 2 and 3.

* Tell AI to be concise and to use R and the tidyverse. Don't let it spit back a page of all sorts of different analysis.

* Outputs names of USMNT members. OK if it hard codes the names in the script.

* Outputs their names to a file. Should be 26. There will be 27 rows in file, including the column names.

### Scene 2

Preceptor Notes 4 and 5.

* Create quarto doc which reads the file and outputs the contents to the HTML. This is our pipeline. Once the pipeline works from start to finish, we can go back and fix individual parts. First, create the MVP --- the minimal viable product --- and then iterate on it.

* Change the script to get their names from Wikipedia and then output to the csv file. Check that the QMD still renders.

### Scene 3

* Download name, dob, ages and club team. Rewrite csv file to include this data.

* Change quarto document to create a histogram of ages. Maybe a horizontal dot plot with each dot labelled would look cooler. Or how about a bar chart of birth modnths?

* Make the quarto document look nice. 

### Scene 4

* Download for all teams. Should be 48 teams, meaning 26*48 = 1248 rows, plus one row of column names.

* Change quarto document to read in all data. Is it correct? How do we know?

* Copy/paste graphic to #class-work channel.

### Scene 5

What other data might we grab? What questions might we look at? Do we have enough data to determine who are the better teams?


## Topics to Mention 

Cold call to tell me one thing about one student in the breakout room.

Review breakout room behavior. One person always sharing, and then doing nothing but what they are told. The TF is "driving,"" telling the screen-sharer what to do. There is a "Sharer" and a "Driver." IN a few weeks, we will have another student do the driving. All other students are doing the work as well.


Iterate between the main room and breakout rooms. Everyone needs to make a project which makes a nice looking plot. If a student is behind, have him share his screen and you help by driving. 

Titles should tell about the variables.
Subtitles give a key takeaway about the plot.
Captions describe the source.
Axis labels should look nice.

Finish with each student posting a nice image to #class-work.
