---
title: "Day 2"
author: "David Kane"
---

## Goal

New Positron project which includes a new Quarto document. Publish to #class-work channel a nice looking scatterplot.

```{r}
#| echo: false
#| warning: false

library(tidyverse)
library(primer.data)

connectedness |> 
  drop_na() |> 
  ggplot(aes(x = population, y = connectedness)) +
    geom_point() +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
    scale_x_log10(labels = scales::comma_format()) +
    labs(title = "US County Populations versus Economic Connectedness",
         subtitle = "Population size does not matter to EC",
         x = "Population",
         y = "Economic Connectedness",
         caption = "Opportunity Insights")
```

## Session 1

Review Preceptor's Note.

Send students to breakout rooms right away. They need to get used to starting on time. Two questions: 

1) Did anyone read the NYT article? If so, tell your classmates about it. 

2) Any initial ideas on how to make our plot for the day? (Make sure you posted it in #class-work before class.)

Don't dawdle! Three minutes at most.

## Session 2

Cold call: Tell me what your group discussed about the two questions.

Start by making a project. Note how it, by default, is placed in my `projects` folder. Note that all this only makes sense if you have done the "01-code" tutorial.

Review Positron window.

Also, make sure that typing library(primer.data) at the Console works for everyone in your room.

Send to rooms so that everyone has this working. 

Don't dawdle. 5 minutes top.

## Session 3

You need to create and publish your own version of the plot in #class-work.

Create a new Quarto document. Load up the libraries you will need. Render. Make sure it doesn't look ugly.

Make sure everyone in your room gets this far, before you (selfishly) forge ahead.

Send them to the breakout rooms to replicate these. Explore the data!

## Session 4

Cold call: Tell me what to do.

Type what they say. Render after the libraries are in.

library(primer.data) 
library(tidyverse)

Note all the garbage which this is producing! The document is ugly. There are two problems: we don't want to see the code and we don't want to see junky output. 

Good. Now, start working on the plot, use a new code chunk. With luck, you get to this stage with at least 45 minutes left.


## Session 5

Try to call them in when they have the basic components of the plot.

Code call: What did you group come up with?

Things that are likely to be tricky: 

* drop_na() to deal with the warnings. 
* bins argument
* scale_x_log10
* labels = scales::comma_format()

Don't tell them these tricks! Make them figure it out themselves! chatGPT is amazing!

## Session 6

Try to call them in when they have the whole plot done, but perhaps without some details.

Code call: What progress has your group made?

## Session 7

Edit my document to include the answer.

Code call: What gave your group the most problems?

Show how my plot solves those problems.
 

Goal: Ensure that everyone in the group posts a graphic. But, once you get to that stage, make your plot better than mine. You can always re-publish! Ask AI for suggestions.

## Extra Questions

Most important thing is that everyone in a breakout room gets to publish. Leave no student behind! But, if the whole group has posted a graphic in #class-work, then, by all means, challenge them to do more.

Font seems tough to read. Are there recommendations for text sizes on web images that we might follow? Ask AI!

Restrict the plot to your five favorite states, then facet by state.

What does the plot mean?

